name: "Scorecard DepsCheck Workflow"
on:
  push:
    branches: [main]
  workflow_dispatch:
    

jobs:
  Run-Main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: ./main

      
